name: common-entities
on:
  push: 
    branches:
    - main
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout to repository
      uses: actions/checkout@v2
    - name: install and build
      run:  ci 
    - name: publish to registery
      uses: actions/setup-node@v2
      with:
       node-version: 16
       registery-url: 'https://npm.pkg.github.com'
       scope: '@Faisalaliarain'
    - run: npm publish
      env:
       NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
